server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
canal.conf:
  mode: tcp
  # 修改成自己canal-deployer启动的ip和端口
  canalServerHost: 172.26.140.252:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout: 100
  #  accessKey:
  #  secretKey:
  srcDataSources:
    defaultDS:
      # 换成自己mysql主库的地址和数据源
      #      url: jdbc:mysql://airiot.tech:3340/iot?useUnicode=true
      #      url: jdbc:mysql://airiot.tech:3340/iot?characterEncoding=utf8&useUnicode=true
      #      url: jdbc:mysql://airiot.tech:3340/iot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      url: jdbc:mysql://airiot.tech:3340/iot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root  # 换成自己mysql主库的账号
      password: 123456  #  换成自己mysql主库的密码
  canalAdapters:
    - instance: example
  groups:
    - groupId: g1
      outerAdapters:
        #    - name: logger
        - name: rdb
          key: mysql1
          properties:
            jdbc.driverClassName: com.mysql.jdbc.Driver
            jdbc.url: jdbc:mysql://airiot.tech:3341/iot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
            jdbc.username: root
            jdbc.password: 123456
